import * as XLSX from 'xlsx';
import { ProductCategory, LOW_STOCK_THRESHOLD } from '../types';

export const VALID_PRODUCT_CATEGORIES: ProductCategory[] = [
  'Writing & Pens',
  'Writing & Correction',
  'Paper & Notebooks',
  'Printing & Copying',
  'Art & Craft',
  'Desk & Office',
  'Binding & Lamination',
  'Packaging & Envelopes',
  'Custom Stamps & Signs',
  'General'
];

/**
 * Generates and triggers download of the standardized Rahel Stationery Excel Template (.xlsx)
 * Designed for effortless bulk import:
 * - Category, SKU, and Barcodes are automatically generated by the system.
 * - Minimum stock threshold is fixed at 3 across all products (no column needed).
 */
export const downloadExcelImportTemplate = () => {
  const wb = XLSX.utils.book_new();

  // --------------------------------------------------------------------------
  // SHEET 1: Products
  // --------------------------------------------------------------------------
  const productsHeaders = [
    'Product Name',
    'Buying Price (ETB)',
    'Selling Price (ETB)',
    'Current Stock',
    'Unit',
    'Description',
    'Barcode (Optional)',
    'SKU (Optional)',
    'Category (Optional)'
  ];

  const exampleRows = [
    [
      'Pilot G2 0.7mm Retractable Gel Pen Black',
      35.0,
      60.0,
      50,
      'pcs',
      'Smooth rollerball gel ink with contoured rubber grip',
      '', // Auto-generated
      '', // Auto-generated
      ''  // Auto-detected
    ],
    [
      'Deli A4 Copy Paper 80gsm (500 Sheets/Ream)',
      380.0,
      480.0,
      40,
      'ream',
      'High opacity multipurpose office printing and copy paper',
      '', // Auto-generated
      '', // Auto-generated
      ''  // Auto-detected
    ],
    [
      'Kangaro Heavy Duty Desktop Stapler No. 10',
      180.0,
      250.0,
      25,
      'pcs',
      'All-metal mechanism with built-in staple remover',
      '', // Auto-generated
      '', // Auto-generated
      ''  // Auto-detected
    ],
    [
      'Camel 12-Shade Acrylic Paint Color Tubes Set',
      240.0,
      360.0,
      15,
      'set',
      'Fast-drying vibrant acrylics for canvas, wood and paper',
      '', // Auto-generated
      '', // Auto-generated
      ''  // Auto-detected
    ],
    [
      'Standard Thermal POS Cash Register Receipt Paper Rolls',
      25.0,
      45.0,
      120,
      'roll',
      'BPA-free thermal paper rolls for cash registers and card terminals',
      '890123456999', // Pre-existing vendor barcode example
      'PRN-THRM-001',
      'Printing & Copying'
    ]
  ];

  const wsProductsData = [productsHeaders, ...exampleRows];
  const wsProducts = XLSX.utils.aoa_to_sheet(wsProductsData);

  // Column widths in characters for clean display
  wsProducts['!cols'] = [
    { wch: 42 }, // Product Name
    { wch: 18 }, // Buying Price (ETB)
    { wch: 18 }, // Selling Price (ETB)
    { wch: 14 }, // Current Stock
    { wch: 10 }, // Unit
    { wch: 45 }, // Description
    { wch: 20 }, // Barcode (Optional)
    { wch: 16 }, // SKU (Optional)
    { wch: 22 }  // Category (Optional)
  ];

  // Freeze top row for easy scrolling
  wsProducts['!views'] = [{ state: 'frozen', ySplit: 1 }];

  XLSX.utils.book_append_sheet(wb, wsProducts, 'Products');

  // --------------------------------------------------------------------------
  // SHEET 2: Instructions
  // --------------------------------------------------------------------------
  const instructionsData = [
    ['RAHEL STATIONERY - BULK INVENTORY IMPORT GUIDE'],
    ['Standard Operating Procedure for Vendor Spreadsheets & Product Setup'],
    [''],
    ['1. AUTOMATIC SYSTEM GENERATION'],
    ['• Category: Automatically assigned based on product title & description (e.g. pens -> Writing, paper -> Paper). Falls back to "General".'],
    ['• SKU: Automatically generated in consistent unique format (e.g. PPR-A4CO-0101). Guaranteed never to duplicate.'],
    ['• Barcode: Automatically generated 12-digit standard scannable barcode for each item. Compatible with barcode scanners.'],
    [`• Minimum Stock: Fixed at ${LOW_STOCK_THRESHOLD} units for all products across the entire system. No input needed.`],
    [''],
    ['2. COLUMN DEFINITIONS & RULES'],
    ['Column Name', 'Required', 'Data Type', 'Description & Accepted Format', 'Example Value'],
    [
      'Product Name',
      'YES',
      'Text',
      'Full descriptive title of the stationery item. Cannot be blank.',
      'Pilot G2 0.7mm Gel Pen'
    ],
    [
      'Buying Price (ETB)',
      'OPTIONAL',
      'Number',
      'Wholesale/purchase cost in ETB. Used for inventory valuation and profit calculations. Defaults to 0 if left blank.',
      '35.00'
    ],
    [
      'Selling Price (ETB)',
      'YES',
      'Number',
      'Retail customer selling price in ETB. Must be a positive number greater than 0.',
      '60.00'
    ],
    [
      'Current Stock',
      'OPTIONAL',
      'Integer',
      'Initial on-hand quantity available in the store. Defaults to 0 if left blank.',
      '50'
    ],
    [
      'Unit',
      'OPTIONAL',
      'Text',
      'Unit of measurement (pcs, ream, box, pack, set, roll, tin, pad, meter). Defaults to "pcs".',
      'pcs'
    ],
    [
      'Description',
      'OPTIONAL',
      'Text',
      'Product features, dimensions, ink color, sheet weight, or specifications.',
      '0.7mm retractable rollerball gel'
    ],
    [
      'Barcode (Optional)',
      'OPTIONAL',
      'Number/Text',
      'Pre-existing manufacturer barcode. If blank, the system automatically generates a unique 12-digit barcode.',
      '890123456001'
    ],
    [
      'SKU (Optional)',
      'OPTIONAL',
      'Text',
      'Custom SKU if you already have one. If left blank, the system automatically generates a unique formatted SKU.',
      'WRI-PILG-0101'
    ],
    [
      'Category (Optional)',
      'OPTIONAL',
      'Text',
      'Specific category override. If left blank, the system automatically assigns the best category.',
      'Writing & Pens'
    ],
    [''],
    ['3. LOW STOCK MONITORING RULE'],
    ['• Stock > 3: Normal stock (Healthy inventory)'],
    ['• Stock = 3: Low stock warning'],
    ['• Stock < 3: Critical stock / Urgent Restock Alert'],
    [''],
    ['4. SUPPORTED PRODUCT CATEGORIES'],
    ['• Writing & Pens'],
    ['• Paper & Notebooks'],
    ['• Printing & Copying'],
    ['• Art & Craft'],
    ['• Desk & Office'],
    ['• Binding & Lamination'],
    ['• Packaging & Envelopes'],
    ['• Custom Stamps & Signs'],
    ['• General']
  ];

  const wsInstructions = XLSX.utils.aoa_to_sheet(instructionsData);
  wsInstructions['!cols'] = [
    { wch: 24 }, // Column Name
    { wch: 12 }, // Required
    { wch: 14 }, // Data Type
    { wch: 55 }, // Description
    { wch: 22 }  // Example Value
  ];

  XLSX.utils.book_append_sheet(wb, wsInstructions, 'Instructions');

  // Trigger Excel file download in browser
  XLSX.writeFile(wb, 'Rahel-Stationery-Product-Import-Template.xlsx');
};
